### PR TITLE
Add a scheme named flat

### PR DESCRIPTION
**Pull request by xxNull-lsk**

### CODE REVIEW

**Comment by IngwiePhoenix** [comment]
Ooooh, this is beautiful!

I have notified the FLTK core developers, so they'll check it out ASAP (:

**Comment by IngwiePhoenix** [comment]
Just tested it and it works on my end. Looks really neat on OS X!

Well, since this is just a mirror, I'll just wait for the FLTK core devs. (:

**Comment by xxNull-lsk** [comment]
input

**Comment by IngwiePhoenix** [comment]
I got ahold of the devs. They told me to redirect you here:

http://fltk.org/str.php

They'd like if you submitted the scheme through the "usual ways" since this repo right here is just a mirror. :)

But it seemed to me that they'll have it merged. I personally like the scheme a lot and actually used the PR to check out how my apps look with it. So, reall ynice stuff.

Good luck on posting it to fltk's str!

**Comment by xxNull-lsk** [comment]
I'm in China. Due to GFW(The Great Fire Wall of China) so I can't access
http://fltk.org/str.php

So I can't submitted the scheme through the "usual ways".
Anyway, thank you for your help.

**Comment by IngwiePhoenix** [comment]
I’ll let the other developers know, maybe we can work something out to get your suggestion into the system.

You can also hit up the google group fltk-devel - that is where I posted too.

**Comment by xxNull-lsk** [comment]
Sorry, I can't access google, twitter, facebook...
Same reason:(

**Comment by Postrediori** [comment]
This theme is very nice and I've been using it for my utilities for quite a time.
FYI There is an official FLTK repository now on GitHub: https://github.com/fltk/fltk

**Comment by IngwiePhoenix** [comment]
Really? Oh god. Gooooood. Git-SVN was acting up badly and so I was almost there to kill the repo and re-initialize it from the base - however, with git-svn throwing checksum missmatches at me all the time, I couldn’t even pull past r4049. :/
But with an official Github repo being there, I don’t need this one anymore. That’s really nice!

**Pull request closed without merging**
